# Use the official Spark image as the base
FROM apache/spark

# Copy your PySpark script into the container
COPY your_pyspark_script.py /opt/your_pyspark_script.py

# Entry point to keep the container running (you can customize this)
CMD ["tail", "-f", "/dev/null"]